services:
  springboot-app:
    build: .
    container_name: springboot-app
    env_file:
      - /home/developer/dev/env/spring-boot.env
    ports:
      - "8082:8080"
    volumes:
      - app_logs:/app/logs   # app writes logs to a named volume
    networks:
      - elk_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    env_file:
      - /home/developer/dev/env/elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ protocol
      - "15672:15672" # RabbitMQ management UI
    env_file:
      - /home/developer/dev/env/rabbitmq.env

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    env_file:
      - /home/developer/dev/env/kibana.env
    ports:
      - "5601:5601"
    networks:
      - elk_net
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    user: root   # required to read mounted config/log files
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - app_logs:/app-logs
    depends_on:
      - elasticsearch
    networks:
      - elk_net

networks:
  elk_net:
    driver: bridge

volumes:
  es_data:
  app_logs:



