services:
  springboot-app:
    build: .
    container_name: springboot-app
    env_file:
      - /home/developer/dev/env/spring-boot.env
    ports:
      - "8082:8080"
    volumes:
      - app_logs:/app/logs   # app writes logs to a named volume
    networks:
      - articles-all-local-services_home_net


networks:
  articles-all-local-services_home_net:
    external: true

volumes:
  app_logs:



