services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    env_file:
      - /home/developer/dev/env/localdb.env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - elk_net
    volumes:
      - ./logs:/app/logs

networks:
  elk_net:
    external:
      name: articles-aop-and-logstash_elk_net
