spring:
  application:
    name: baseline-api
  profiles:
    active: local-baseline
  config:
    import: "optional:configserver:http://10.0.0.191:5671"

  cloud:
    config:
      name: local

server:
  servlet:
    context-path: /api/v1

