apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baseline-api
  template:
    metadata:
      labels:
        app: baseline-api
    spec:
      containers:
        - name: baseline-api
          image: ${ECR_REGISTRY}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: springboot-creds
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health

          volumeMounts:
            - name: logs-volume
              mountPath: logs

        - name: log-shipper
          image: amazon/aws-cli:2.28.26
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              while true; do
                for file in /logs/*.json; do
                  [ -e "$file" ] || continue
                  aws s3 cp "$file" s3://eks-k8s-cluser-pod-logs098878681/logs/
                done
                sleep 30
              done

          envFrom:
            - secretRef:
                name: aws-creds
          volumeMounts:
            - name: logs-volume
              mountPath: /logs


      volumes:
        - name: logs-volume
          emptyDir: {}
