apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baseline-api
  template:
    metadata:
      labels:
        app: baseline-api
    spec:
      containers:
        - name: baseline-api
          image: ${ECR_REGISTRY}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-credentials
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health
          volumeMounts:
            - mountPath: /logs
              name: efs-volume
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: efs-pvc