apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baseline-api
  template:
    metadata:
      labels:
        app: baseline-api
    spec:
      containers:
        - name: baseline-api
          image: ${ECR_REGISTRY}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-credentials
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health
          volumeMounts:
            - mountPath: /logs
              name: efs-volume

        - name: s2-shipper-side-car
          image: amazon/aws-cli
          command:
            - sh
            - -c
            - |
              while true; do
               aws s3 cp /logs s3://eks-k8s-cluser-pod-logs098878681/logs/${POD_NAMESPACE}/${POD_NAME}/ --recursive --quiet || true
                sleep 60
              done

      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: efs-pvc