apiVersion: v1
kind: Service
metadata:
  name: baseline-api
  namespace: dev
spec:
  selector:
    app: baseline-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

