name: Build & Push Docker Image to ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: af-south-1               # update if needed
  ECR_REPOSITORY: dev-ecr-repo          # your ECR repo name

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: ./mvnw clean package -DskipTests -Dspring.profiles.active=ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image
        run: |
          COMMIT_HASH=${GITHUB_SHA::7}
          IMAGE_TAG=$COMMIT_HASH
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}

          echo "Building Docker image..."
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .

          echo "Pushing to ECR..."
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

          echo "Image pushed: $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"
